feat: added scyllaDB for go gin server
intelops/compage-template-go pull request #20
Opened 2023-11-28 12:05 UTC by MrAzharuddin

Hi @mahendraintelops ,

This PR contains the template for scylla DB integration for go-gin-server.

2023-12-07 06:51 UTC, mahendraintelops submitted a review, later dismissed

2023-12-07 06:51 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
Please keep this what it was before

2023-12-07 06:51 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Please keep this what it was before

2023-12-07 08:01 UTC, azar-writes-code commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
Sure @mahendraintelops

2023-12-07 08:01 UTC, MrAzharuddin commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Sure @mahendraintelops

2023-12-07 08:10 UTC, azar-writes-code commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Done with changes @mahendraintelops

2023-12-07 08:11 UTC, azar-writes-code commented on frameworks/go-gin-server/pkg/rest/server/controllers/sqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
Done @mahendraintelops

2023-12-25 09:50 UTC, mahendraintelops requested changes

2023-12-25 09:50 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
please dont change this and keep the same as it was earlier

2023-12-25 09:50 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
please dont change this and keep the same as it was earlier

2023-12-25 09:50 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-column-based-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
please add the same response as its for other delete methods

2023-12-25 09:50 UTC, mahendraintelops commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-column-based-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Please add the response here too

2023-12-26 08:55 UTC, MrAzharuddin commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Hi @mahendraintelops, Changes are made as suggested, Please let me know if anything needed

2023-12-26 08:55 UTC, MrAzharuddin commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
Hi @mahendraintelops, Changes are made as suggested, Please let me know if anything needed

2023-12-26 08:55 UTC, MrAzharuddin commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-column-based-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} deleted successfully"})
Hi @mahendraintelops, Changes are made as suggested, Please let me know if anything needed

2023-12-26 08:55 UTC, MrAzharuddin commented on frameworks/go-gin-server/pkg/rest/server/controllers/nosqls-column-based-controller.go.tmpl
> +	context.JSON(http.StatusOK, gin.H{"message": "{{.CapsResourceNameSingular}} updated successfully"})
Hi @mahendraintelops, Changes are made as suggested, Please let me know if anything needed

2024-01-08 12:36 UTC, closed without merging